version: "3"

services:
  openweathermap:
    image: "${IMAGE_PREFIX}openweathermap-image:${IMAGE_TAG:-latest}"
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./global.d.ts:/code/global.d.ts
      - ./server.ts:/code/server.ts
      - ./tsconfig.json:/code/tsconfig.json
      - ./src:/code/src/
    ports:
      - "8080:8000"
    # networks:
    #   - some-external-network
    working_dir: /code
    command: watch

# networks:
#   some-external-network:
#     external:
#       name: some-external-network
